import { createContext, useContext, useEffect, useMemo, useState } from 'react';

const UIContext = createContext(null);

const fa = {
  dir: 'rtl',
  langName: 'English',
  siteName: 'گروه هتل‌های لاله',
  siteNameShort: 'هتل لاله',
  themeLight: 'لایت',
  themeDark: 'دارک',
  darkMode: 'حالت شب',
  lightMode: 'حالت روز',
  bookNow: 'رزرو',
  bookOnline: 'رزرو آنلاین',
  allRights: 'تمام حقوق محفوظ است.',
  nav: {
    home: 'صفحه اصلی', rooms: 'اتاق‌ها و سوئیت‌ها', dining: 'رستوران‌ها', branches: 'گروه هتل‌های لاله', wellness: 'امکانات', gallery: 'گالری', blog: 'بلاگ و اخبار', about: 'درباره ما', contact: 'تماس با ما', booking: 'رزرو آنلاین'
  },
  hero: {
    badge: 'گروه هتل‌های بین‌المللی لاله',
    titleA: 'جایی که شما',
    titleB: 'ستاره‌اید',
    desc: 'اقامتی لوکس با امکاناتی مدرن و خدماتی متمایز در همسایگی پارک لاله؛ جایی برای مکثی آرام میان هیاهوی پایتخت.',
    reserve: 'رزرو اتاق',
    video: 'مشاهده ویدیو',
    bullets: ['موقعیت مرکزی', 'امکانات لوکس', 'رستوران‌های متنوع', 'سالن‌های همایش']
  },
  home: {
    aboutEyebrow: 'درباره تجربه اقامت',
    aboutTitle: 'مکثی آراسته به هنر، وقار و آرامش در میانه شتاب شهر',
    aboutText: 'گروه هتل‌های لاله در همسایگی سبز پارک لاله و نزدیک مراکز فرهنگی و اداری پایتخت قرار دارد. تلفیق طراحی مدرن با میراث پنجاه‌ساله مهمان‌نوازی ایرانی، تجربه‌ای خاص از اقامت را رقم می‌زند.',
    aboutCta: 'داستان هتل را بخوانید',
    benefitsHeadline: 'چرا لاله؟',
    benefitsTitle: 'مزایایی که اقامت را بی‌رقیب می‌کند',
    benefitsText: 'امکاناتی که هر اقامت را به تجربه‌ای به‌یادماندنی تبدیل می‌کند.',
    roomsTitle: 'اتاق‌هایی با چشم‌انداز تهران و پارک لاله',
    roomsText: 'انتخاب و رزرو مستقیم از بین اتاق‌ها و سوئیت‌های هتل.',
    roomDetail: 'جزئیات و رزرو',
    diningTitle: 'چهار رستوران، چهار حال‌و‌هوا',
    diningText: 'ایوان، حافظیه، فرانسوی و تیاره؛ از طعم‌های اصیل ایرانی تا گریل و منوی بین‌المللی.',
    diningCta: 'مشاهده منوها',
    packagesTitle: 'پکیج‌های آماده برای سفر و رویداد',
    packagesCta: 'رزرو پکیج',
    testimonialsEyebrow: 'صدای مهمانان',
    testimonialsTitle: 'حس اقامت پنج‌ستاره در مرکز تهران',
    testimonialsText: 'نزدیکی به پارک، کیفیت خدمات، صبحانه متنوع و رفتار حرفه‌ای پرسنل از مهم‌ترین دلایل انتخاب دوباره گروه هتل‌های لاله است.',
    testimonialsCta: 'درخواست مشاوره اقامت',
    eventsTitle: 'رویدادهای تازه هتل',
    eventsMore: 'بیشتر',
    features: ['صبحانه رایگان', 'استخر و سونا', 'پارکینگ اختصاصی', 'دسترسی مرکزی']
  },
  blog: {
    eyebrow: 'وبلاگ و اخبار',
    title: 'آخرین رویدادها و نوشته‌های هتل لاله',
    text: 'از اخبار هتل و رویدادهای ویژه تا داستان‌های سفر و فرهنگ ایران',
    all: 'همه',
    emptyTitle: 'هنوز نوشته‌ای منتشر نشده',
    emptyText: 'به زودی جدیدترین اخبار و رویدادهای گروه هتل‌های لاله را اینجا بخوانید.',
    featured: 'جدیدترین',
    readMore: 'ادامه مطلب',
    back: 'بازگشت به بلاگ',
    notFoundTitle: 'نوشته‌ای یافت نشد',
    notFoundText: 'مطلب مورد نظر وجود ندارد یا حذف شده است.',
    share: 'اشتراک‌گذاری:',
    copyLink: 'کپی لینک',
    related: 'نوشته‌های مرتبط',
    categories: 'دسته‌بندی‌ها',
    bookingCta: 'رزرو اقامت',
    bookingText: 'برای تجربه اقامتی لوکس در گروه هتل‌های لاله، همین حالا رزرو کنید.'
  },
  booking: {
    title: 'رزرو آنلاین',
    text: 'اتاق مورد نظر خود را انتخاب کنید و با بهترین نرخ‌ها اقامت خود را در گروه هتل‌های لاله رزرو نمایید.',
    checkin: 'ورود',
    checkout: 'خروج',
    adult: 'بزرگسال',
    child: 'کودک',
    roomType: 'نوع اتاق',
    perNight: '/ شب',
    extras: 'خدمات اضافه',
    fullName: 'نام و نام خانوادگی',
    fullNamePlaceholder: 'مثلاً نیما رضایی',
    phone: 'شماره تماس',
    phonePlaceholder: '۰۹xxxxxxxxx',
    email: 'ایمیل',
    bestRate: 'بهترین نرخ‌ها در گروه هتل‌های لاله',
    whyTitle: 'چرا هتل لاله؟',
    roomPrices: 'قیمت اتاق‌ها',
    phoneTitle: 'رزرو تلفنی',
    phoneText: 'برای رزرو تلفنی یا اطلاعات بیشتر با ما تماس بگیرید:',
    phoneSupport: 'پشتیبانی ۲۴ ساعته، ۷ روز هفته',
    pricesTitle: 'قیمت پایه اتاق‌ها',
    pricesText: 'قیمت‌ها بر اساس هر شب اقامت می‌باشند. مالیات و خدمات به مبلغ نهایی اضافه می‌گردد.',
    room: 'اتاق',
    duration: 'مدت',
    nights: 'شب',
    amount: 'مبلغ',
    tax: 'مالیات و خدمات',
    total: 'مبلغ نهایی',
    extrasTotal: 'خدمات اضافه',
    confirmTitle: 'رزرو با موفقیت ثبت شد',
    confirmCode: 'کد پیگیری شما',
    confirmSave: 'اطلاعات رزرو شما در سیستم ذخیره شد. در صورت اتصال به دیتابیس، اطلاعات به صورت خودکار در پنل ادمین قابل مشاهده است.',
    newBooking: 'رزرو جدید',
    errorDate: 'تاریخ خروج باید حداقل یک شب بعد از تاریخ ورود باشد.',
    errorCapacity: 'ظرفیت این اتاق برای تعداد مهمانان انتخابی کافی نیست.',
    errorInvalid: 'تاریخ‌ها معتبر نیستند.',
    errorRequired: 'نام و شماره تماس برای ثبت رزرو الزامی است.',
    submitText: 'تکمیل و ثبت رزرو',
    searchText: 'جستجو و رزرو',
    saving: 'در حال ثبت...',
    highlights: [
      { icon: 'ParkingCircle', title: 'پارکینگ رایگان', text: 'پارکینگ اختصاصی هتل با ظرفیت بالا' },
      { icon: 'Globe2', title: 'اینترنت پرسرعت', text: 'وای‌فای رایگان در تمام فضاهای هتل' },
      { icon: 'Waves', title: 'استخر و سونا', text: 'استخر سرپوشیده، سونا و جکوزی مدرن' },
      { icon: 'UtensilsCrossed', title: 'رستوران‌های متنوع', text: '۵ رستوران با انواع غذاهای ایرانی و بین‌المللی' },
      { icon: 'Dumbbell', title: 'باشگاه ورزشی', text: 'باشگاه بدنسازی مجهز با امکانات روز' },
      { icon: 'ConciergeBell', title: 'پذیرش ۲۴ ساعته', text: 'خدمات پذیرش و concierge در تمام ساعات' },
    ]
  },
  rooms: {
    title: 'اتاق‌ها و سوئیت‌های گروه هتل‌های لاله',
    text: 'صفحات مستقل، فیلتر، مرتب‌سازی، گالری و رزرو مستقیم برای هر اتاق آماده است.',
    all: 'همه',
    rooms: 'اتاق‌ها',
    suites: 'سوئیت‌ها',
    sortFeatured: 'پیشنهادی',
    sortPrice: 'ارزان‌ترین',
    sortCapacity: 'ظرفیت بیشتر',
    capacity: 'ظرفیت',
    persons: 'نفر',
    fromPrice: 'شروع قیمت',
    details: 'جزئیات',
    reserve: 'رزرو',
    size: 'متراژ',
    bed: 'تخت',
    view: 'چشم‌انداز',
    amenities: 'امکانات اتاق',
    pricePerNight: 'قیمت هر شب',
    bookingTitle: 'ظرفیت را بررسی و رزرو را ثبت کنید'
  },
  dining: {
    title: 'رستوران‌ها و کافی‌شاپ هتل لاله',
    text: 'ایوان، حافظیه، فرانسوی و تیاره؛ منوها، ساعت کاری و رزرو میز در یک تجربه مدرن.',
    menuPreview: 'پیشنهادهای منو',
    reservationTitle: 'رزرو میز رستوران',
    reservationText: 'فرم رزرو میز کار می‌کند و درخواست‌ها را داخل مرورگر ذخیره می‌کند.',
    successText: 'درخواست شما ثبت شد؛ تیم میزبان با شما تماس می‌گیرد.',
    restaurantLabel: 'رستوران',
    dateLabel: 'تاریخ',
    timeLabel: 'ساعت',
    guestsLabel: 'تعداد نفرات',
    nameLabel: 'نام',
    namePlaceholder: 'نام شما',
    phoneLabel: 'تماس',
    phonePlaceholder: '۰۹xxxxxxxxx',
    submit: 'ثبت رزرو میز'
  },
  events: {
    title: 'سالن‌های همایش و رویداد',
    text: 'از مراسم بزرگ تا جلسه مدیریتی؛ سالن گلزار و سنبل با چیدمان منعطف، نور، صدا، پذیرایی و پارکینگ اختصاصی.',
    typeLabel: 'نوع رویداد',
    hallLabel: 'سالن پیشنهادی',
    dateLabel: 'تاریخ',
    guestsLabel: 'تعداد مهمان',
    nameLabel: 'نام',
    phoneLabel: 'شماره تماس',
    descLabel: 'توضیحات',
    descPlaceholder: 'نیازهای پذیرایی، نور، صدا و چیدمان',
    submit: 'ارسال درخواست رزرو سالن',
    successText: 'درخواست شما ثبت شد.',
    options: ['همایش', 'جلسه کاری', 'عروسی / جشن', 'مراسم فرهنگی'],
    perksTitle: 'یک تیم تشریفات، همه جزئیات',
    perksText: 'از انتخاب سالن و چیدمان تا منوی پذیرایی؛ تیم رویداد هتل لاله در هر مرحله همراه شماست.',
    newsTitle: 'خبرها و رویدادهای گروه هتل‌های لاله',
    share: 'اشتراک‌گذاری'
  },
  contact: {
    title: 'تماس با گروه هتل‌های لاله',
    text: 'رزرو اقامت، سالن، رستوران یا خدمات ویژه؛ فرم تماس کار می‌کند و پیام‌ها را ذخیره می‌کند.',
    infoTitle: 'همیشه آماده میزبانی هستیم',
    addressLabel: 'آدرس هتل',
    phoneLabel: 'تلفن',
    emailLabel: 'ایمیل',
    centralLabel: 'دفتر مرکزی گروه',
    subjectLabel: 'موضوع',
    subjectOptions: ['رزرو اتاق', 'رزرو سالن', 'رستوران', 'همکاری و پیشنهاد'],
    nameLabel: 'نام',
    phoneInput: 'شماره تماس',
    emailInput: 'ایمیل',
    messageLabel: 'پیام',
    submit: 'ارسال پیام',
    successText: 'پیام ثبت شد؛ در نسخه نهایی به CRM یا ایمیل هتل ارسال می‌شود.',
    mapTitle: 'نقشه مفهومی دسترسی',
    mapHotel: 'هتل لاله تهران',
    mapPark: 'پارک لاله',
    mapStreet: 'بلوار کشاورز',
    mapMuseum: 'موزه هنرهای معاصر',
    mapSquare: 'میدان ولیعصر'
  },
  gallery: {
    title: 'گالری تصاویر گروه هتل‌های لاله',
    text: 'گالری قابل فیلتر با Lightbox، آماده اتصال به CMS تصاویر هتل.',
    altTitle: 'تصاویر اقامت، غذا، رویداد و تهران',
    all: 'همه',
    categories: ['اتاق‌ها', 'رستوران', 'هتل', 'رویداد', 'تهران'],
    items: [
      { title: 'لابی و پذیرش', cat: 'هتل' },
      { title: 'لانژ و فضای عمومی', cat: 'هتل' },
      { title: 'سالن رویداد', cat: 'رویداد' },
      { title: 'پارک لاله', cat: 'تهران' },
    ]
  },
  about: {
    title: 'درباره گروه هتل‌های بین‌المللی لاله',
    text: 'زنجیره‌ای با ریشه در سال ۱۳۴۹ و تمرکز بر مهمان‌نوازی ایرانی و استانداردهای بین‌المللی؛ از تهران تا کندوان، سرعین، بیستون و چابهار.',
    headline: 'از میراث اینترکنتیننتال تا نسل تازه هتل‌داری ایرانی',
    paragraph1: 'گروه هتل‌های بین‌المللی لاله با هدف ارائه تجربه‌ای ممتاز در هتلداری فعالیت خود را آغاز کرد. هتل لاله تهران به عنوان قلب این برند، امروز پس از نوسازی کامل، گذشته پرافتخار خود را با امکانات روز، طراحی مدرن و میزبانی ایرانی پیوند می‌زند.',
    paragraph2: 'در این بازطراحی، روایت برند از یک وب‌سایت قدیمی به یک تجربه دیجیتال سینمایی تبدیل شده؛ تجربه‌ای که کاربر را از الهام تا رزرو، رویداد، رستوران و تماس بدون اصطکاک جلو می‌برد.',
    alt: 'هتل لاله تهران',
    roomsLabel: 'اتاق و سوئیت',
    snapshotTitle: 'لاله در یک نگاه'
  },
  wellness: {
    title: 'امکانات رفاهی، تندرستی و خدمات اقامتی',
    text: 'استخر، سونا، جکوزی، ماساژ، باشگاه ورزشی، پارکینگ، لاندری و خدمات اقامتی برای تجربه‌ای کامل در مرکز تهران.',
    sectionTitle: 'خدماتی که اقامت را کامل می‌کند',
    alt: 'امکانات هتل لاله',
    headline: 'بعد از تهران شلوغ، وارد سکوت طلایی شوید',
    description: 'طراحی صفحه امکانات طوری انجام شده که بتواند به ماژول‌های رزرو اسپا، باشگاه و خدمات VIP متصل شود. در نسخه فعلی تمام CTAها کاربر را به صفحه تماس یا رزرو هدایت می‌کنند.'
  },
  branches: {
    eyebrow: 'Laleh Hotels Group',
    title: 'یک برند، چند تجربه متفاوت در ایران',
    text: 'از مرکز تهران تا صخره‌های کندوان، آب‌درمانی سرعین، کاروانسرای بیستون و ساحل چابهار؛ شعب گروه لاله هر کدام روایت ویژه‌ای از اقامت ایرانی دارند.',
    cta: 'مشاهده شعبه',
    detailTitle: 'تجربه این شعبه',
    otherTitle: 'دیگر شعب گروه لاله',
  },
  tehran: {
    title: 'جاذبه‌های اطراف گروه هتل‌های لاله',
    sectionTitle: 'از اتاق تا تهران فرهنگی فقط چند دقیقه',
    headline: 'برنامه تهران‌گردی شخصی‌سازی‌شده',
    text: 'کانسیرج هتل می‌تواند مسیرهای هنری، تاریخی، خرید، غذا و سفر کاری را با زمان‌بندی دقیق برای شما برنامه‌ریزی کند.',
    hotel: 'هتل لاله تهران',
    park: 'پارک لاله',
    museum: 'موزه هنرهای معاصر',
    carpet: 'موزه فرش',
    heroText: 'همسایه پارک لاله، نزدیک موزه هنرهای معاصر، میدان ولیعصر و محورهای اداری مرکز تهران',
  },
  footer: {
    aboutText: 'گروه هتل‌های بین‌المللی لاله با بیش از ۵۰ سال تجربه مهمان‌نوازی ایرانی؛ از تهران تا کندوان، سرعین، بیستون و چابهار.',
    explore: 'دسترسی سریع',
    experience: 'تجربه هتل',
    contact: 'تماس با هتل',
    since: 'از ۱۳۴۹',
  },
  notFound: {
    title: 'این اتاق در دسترس نیست!',
    text: 'صفحه‌ای که دنبالش هستید پیدا نشد. از مسیرهای اصلی سایت ادامه دهید.',
    cta: 'بازگشت به خانه'
  },
  quick: ['پارکینگ رایگان', 'اینترنت پرسرعت', 'استخر و سونا', 'پذیرش ۲۴ ساعته'],
    aboutMini: {
    eyebrow: 'درباره گروه هتل‌های لاله',
    title: 'اقامتی خاطره‌انگیز در هتلی با اصالت',
    text: 'گروه هتل‌های بین‌المللی لاله با بیش از ۵۵ سال سابقه درخشان در میزبانی از مهمانان داخلی و خارجی، با ارائه بهترین خدمات و امکانات روز دنیا تجربه‌ای متفاوت از مهمان‌نوازی ایرانی را رقم می‌زند.',
    more: 'درباره ما بیشتر بدانید',
    facilities: 'امکانات هتل'
  },
  common: { details: 'جزئیات', reserve: 'رزرو', viewAll: 'مشاهده همه', from: 'از' },
  editor: { h2: 'تیتر ۲', h3: 'تیتر ۳', bold: 'پررنگ', italic: 'ایتالیک', underline: 'زیرخط', ul: 'لیست نامرتب', ol: 'لیست مرتب', link: 'لینک' },
  admin: {
    dashboard: 'داشبورد',
    reservations: 'رزروها',
    posts: 'نوشته‌ها',
    loginTitle: 'پنل مدیریت',
    loginPassword: 'رمز عبور را وارد کنید',
    loginError: 'رمز اشتباه',
    loginButton: 'ورود',
    defaultAuthor: 'مدیر هتل',
    postSaved: 'نوشته ذخیره شد ✓',
    postPublished: 'نوشته منتشر شد ✓',
    postUpdated: 'نوشته ویرایش شد ✓',
    deleteConfirm: 'مطمئنی می‌خوای این نوشته رو حذف کنی؟',
    postDeleted: 'نوشته حذف شد',
    adminPanel: 'پنل مدیریت هتل لاله',
    logout: 'خروج',
    totalBookings: 'مجموع رزروها',
    blogPosts: 'نوشته‌های بلاگ',
    totalRevenue: 'مجموع درآمد (تومان)',
    categories: 'دسته‌بندی‌ها',
    recentBookings: 'آخرین رزروها',
    noBookings: 'رزروی ثبت نشده',
    guest: 'مهمان',
    room: 'اتاق',
    amount: 'مبلغ',
    date: 'تاریخ',
    currencyUnit: 'تومان',
    popularTags: 'برچسب‌های پرکاربرد',
    noTags: 'برچسبی وجود ندارد',
    postCount: 'نوشته',
    searchPlaceholder: 'جستجوی کد / نام / تلفن / ایمیل...',
    noSearchResults: 'رزروی با این مشخصات پیدا نشد',
    newPost: 'نوشته جدید',
    firstPost: 'اولین نوشته رو اضافه کن',
    edit: 'ویرایش',
    delete: 'حذف',
    editPost: 'ویرایش نوشته',
    newPostTitle: 'نوشته جدید',
    titleField: 'عنوان',
    contentField: 'متن کامل',
    imageField: 'تصویر',
    imageHint: 'یا لینک مستقیم:',
    authorField: 'نویسنده',
    tagsField: 'برچسب‌ها (با کاما)',
    tagsPlaceholder: 'اخبار, رویداد',
    saving: 'در حال ذخیره...',
    saveChanges: 'ذخیره تغییرات',
    publish: 'انتشار',
    code: 'کد',
    phone: 'تلفن',
    email: 'ایمیل',
    checkin: 'ورود',
    checkout: 'خروج',
    nights: 'شب',
    regDate: 'تاریخ ثبت',
    content: 'محتوا',
  }
};

const en = {
  dir: 'ltr',
  langName: 'فارسی',
  siteName: 'Laleh Hotels Group',
  siteNameShort: 'Laleh Hotel',
  themeLight: 'Light',
  themeDark: 'Dark',
  darkMode: 'Dark Mode',
  lightMode: 'Light Mode',
  bookNow: 'Book',
  bookOnline: 'Book Online',
  allRights: 'All rights reserved.',
  nav: {
    home: 'Home', rooms: 'Rooms & Suites', dining: 'Dining', branches: 'Laleh Hotels Group', wellness: 'Facilities', gallery: 'Gallery', blog: 'Journal', about: 'About', contact: 'Contact', booking: 'Book Online'
  },
  hero: {
    badge: 'Laleh International Hotels Group',
    titleA: 'Where',
    titleB: 'You\'re the Star',
    desc: 'A refined five-star stay beside Laleh Park, blending Iranian hospitality, modern comfort and a calm pause in the middle of the capital.',
    reserve: 'Book a Room',
    video: 'Watch Video',
    bullets: ['Central location', 'Luxury facilities', 'Diverse restaurants', 'Event halls']
  },
  home: {
    aboutEyebrow: 'About the Experience',
    aboutTitle: 'A poised pause amid the city\'s rush, adorned with art, dignity and tranquility',
    aboutText: 'Laleh Hotels Group sits beside the green expanse of Laleh Park, close to the capital\'s cultural and business hubs. A blend of modern design and fifty years of Iranian hospitality heritage creates a unique stay experience.',
    aboutCta: 'Read the hotel story',
    benefitsHeadline: 'Why Laleh?',
    benefitsTitle: 'Benefits that make your stay unmatched',
    benefitsText: 'Facilities that turn every stay into a memorable experience.',
    roomsTitle: 'Rooms with a view of Tehran and Laleh Park',
    roomsText: 'Choose and book directly from the hotel\'s rooms and suites.',
    roomDetail: 'Details & Book',
    diningTitle: 'Four restaurants, four atmospheres',
    diningText: 'Ivan, Hafeziyeh, French and Tiyareh; from authentic Persian flavors to grilled and international menus.',
    diningCta: 'View Menus',
    packagesTitle: 'Ready packages for travel and events',
    packagesCta: 'Book Package',
    testimonialsEyebrow: 'Guest Voice',
    testimonialsTitle: 'The feeling of a five-star stay in central Tehran',
    testimonialsText: 'Proximity to the park, service quality, varied breakfast and professional staff are the top reasons guests choose Laleh Hotels again.',
    testimonialsCta: 'Request Stay Consultation',
    eventsTitle: 'Latest Hotel Events',
    eventsMore: 'More',
    features: ['Free Breakfast', 'Pool & Sauna', 'Private Parking', 'Central Access']
  },
  blog: {
    eyebrow: 'Journal & News',
    title: 'Latest events and posts from Laleh Hotel',
    text: 'From hotel news and special events to travel stories and Iranian culture',
    all: 'All',
    emptyTitle: 'No posts published yet',
    emptyText: 'Soon you\'ll read the latest news and events from Laleh Hotels here.',
    featured: 'Latest',
    readMore: 'Read more',
    back: 'Back to Journal',
    notFoundTitle: 'Post not found',
    notFoundText: 'The requested post does not exist or has been deleted.',
    share: 'Share:',
    copyLink: 'Copy Link',
    related: 'Related Posts',
    categories: 'Categories',
    bookingCta: 'Book Your Stay',
    bookingText: 'Book your luxury stay at Laleh Hotels now.'
  },
  booking: {
    title: 'Online Reservation',
    text: 'Select your preferred room and book your stay at Laleh Hotels with the best rates.',
    checkin: 'Check-in',
    checkout: 'Check-out',
    adult: 'Adult',
    child: 'Child',
    roomType: 'Room Type',
    perNight: '/ night',
    extras: 'Extra Services',
    fullName: 'Full Name',
    fullNamePlaceholder: 'e.g. John Smith',
    phone: 'Phone',
    phonePlaceholder: '+98 9xx xxx xxxx',
    email: 'Email',
    bestRate: 'Best rates at Laleh Hotels',
    whyTitle: 'Why Laleh Hotel?',
    roomPrices: 'Room Prices',
    phoneTitle: 'Phone Reservation',
    phoneText: 'Call us for phone reservations or more information:',
    phoneSupport: '24/7 support, 7 days a week',
    pricesTitle: 'Base Room Prices',
    pricesText: 'Prices are per night. Tax and service charges will be added to the final amount.',
    room: 'Room',
    duration: 'Duration',
    nights: 'nights',
    amount: 'Amount',
    tax: 'Tax & Service',
    total: 'Total',
    extrasTotal: 'Extra Services',
    confirmTitle: 'Reservation Confirmed',
    confirmCode: 'Your Tracking Code',
    confirmSave: 'Your booking has been saved. If the database is connected, it will appear in the admin panel.',
    newBooking: 'New Booking',
    errorDate: 'Check-out must be at least one night after check-in.',
    errorCapacity: 'This room\'s capacity is not enough for the selected guests.',
    errorInvalid: 'The dates are not valid.',
    errorRequired: 'Name and phone number are required.',
    submitText: 'Complete & Confirm',
    searchText: 'Search & Book',
    saving: 'Saving...',
    highlights: [
      { icon: 'ParkingCircle', title: 'Free Parking', text: 'Hotel\'s dedicated high-capacity parking' },
      { icon: 'Globe2', title: 'High-speed Internet', text: 'Free Wi-Fi in all hotel areas' },
      { icon: 'Waves', title: 'Pool & Sauna', text: 'Indoor pool, sauna and modern jacuzzi' },
      { icon: 'UtensilsCrossed', title: 'Diverse Restaurants', text: '5 restaurants with Persian and international cuisine' },
      { icon: 'Dumbbell', title: 'Fitness Center', text: 'Fully equipped modern gymnasium' },
      { icon: 'ConciergeBell', title: '24h Reception', text: 'Reception and concierge service around the clock' },
    ]
  },
  rooms: {
    title: 'Rooms & Suites at Laleh Hotels',
    text: 'Independent pages, filtering, sorting, gallery and direct booking for each room.',
    all: 'All',
    rooms: 'Rooms',
    suites: 'Suites',
    sortFeatured: 'Featured',
    sortPrice: 'Lowest Price',
    sortCapacity: 'Highest Capacity',
    capacity: 'Capacity',
    persons: 'persons',
    fromPrice: 'From',
    details: 'Details',
    reserve: 'Book',
    size: 'Size',
    bed: 'Bed',
    view: 'View',
    amenities: 'Amenities',
    pricePerNight: 'Price per Night',
    bookingTitle: 'Check availability and book'
  },
  dining: {
    title: 'Restaurants & Cafés at Laleh Hotel',
    text: 'Ivan, Hafeziyeh, French and Tiyareh; menus, hours and table reservations in one modern experience.',
    menuPreview: 'Menu Highlights',
    reservationTitle: 'Restaurant Table Reservation',
    reservationText: 'The reservation form works and saves requests in your browser.',
    successText: 'Your request has been submitted; the host team will contact you.',
    restaurantLabel: 'Restaurant',
    dateLabel: 'Date',
    timeLabel: 'Time',
    guestsLabel: 'Guests',
    nameLabel: 'Name',
    namePlaceholder: 'Your name',
    phoneLabel: 'Phone',
    phonePlaceholder: '+98 9xx xxx xxxx',
    submit: 'Submit Reservation'
  },
  events: {
    title: 'Event & Conference Halls',
    text: 'From grand ceremonies to executive meetings; Golzar and Sonbol halls with flexible layout, lighting, sound, catering and dedicated parking.',
    typeLabel: 'Event Type',
    hallLabel: 'Suggested Hall',
    dateLabel: 'Date',
    guestsLabel: 'Number of Guests',
    nameLabel: 'Name',
    phoneLabel: 'Phone Number',
    descLabel: 'Description',
    descPlaceholder: 'Catering, lighting, sound and layout needs',
    submit: 'Submit Hall Request',
    successText: 'Your request has been submitted.',
    options: ['Conference', 'Business Meeting', 'Wedding / Celebration', 'Cultural Event'],
    perksTitle: 'One events team, all the details',
    perksText: 'From hall selection and layout to catering menu; the Laleh Hotel events team is with you every step.',
    newsTitle: 'News & Events at Laleh Hotels',
    share: 'Share'
  },
  contact: {
    title: 'Contact Laleh Hotels Group',
    text: 'Reserve a stay, hall, restaurant or special services; the form works and saves messages.',
    infoTitle: 'Always ready to host you',
    addressLabel: 'Hotel Address',
    phoneLabel: 'Phone',
    emailLabel: 'Email',
    centralLabel: 'Group Head Office',
    subjectLabel: 'Subject',
    subjectOptions: ['Room Reservation', 'Hall Reservation', 'Restaurant', 'Partnership & Suggestion'],
    nameLabel: 'Name',
    phoneInput: 'Phone Number',
    emailInput: 'Email',
    messageLabel: 'Message',
    submit: 'Send Message',
    successText: 'Message saved; in the final version it will be sent to the hotel CRM or email.',
    mapTitle: 'Access Concept Map',
    mapHotel: 'Laleh Tehran Hotel',
    mapPark: 'Laleh Park',
    mapStreet: 'Keshavarz Blvd',
    mapMuseum: 'Museum of Contemporary Art',
    mapSquare: 'Valiasr Square'
  },
  gallery: {
    title: 'Laleh Hotels Photo Gallery',
    text: 'Filterable gallery with Lightbox, ready for hotel CMS image connection.',
    altTitle: 'Images of accommodation, food, events and Tehran',
    all: 'All',
    categories: ['Rooms', 'Restaurant', 'Hotel', 'Events', 'Tehran'],
    items: [
      { title: 'Lobby & Reception', cat: 'Hotel' },
      { title: 'Lounge & Public Spaces', cat: 'Hotel' },
      { title: 'Event Hall', cat: 'Events' },
      { title: 'Laleh Park', cat: 'Tehran' },
    ]
  },
  about: {
    title: 'About Laleh International Hotels Group',
    text: 'A chain rooted in 1970 with a focus on Iranian hospitality and international standards; from Tehran to Kandovan, Sareyn, Bistoon and Chabahar.',
    headline: 'From Intercontinental heritage to a new generation of Iranian hospitality',
    paragraph1: 'Laleh International Hotels Group started with the goal of providing an exceptional hospitality experience. Laleh Tehran Hotel, as the heart of this brand, now blends its proud past with modern amenities, contemporary design and Iranian hosting after a complete renovation.',
    paragraph2: 'In this redesign, the brand narrative has been transformed from an old website into a cinematic digital experience — one that takes the user from inspiration to booking, events, dining and contact without friction.',
    alt: 'Laleh Hotels Group',
    roomsLabel: 'rooms & suites',
    snapshotTitle: 'Laleh at a Glance'
  },
  wellness: {
    title: 'Wellness, Leisure & Hospitality Services',
    text: 'Pool, sauna, jacuzzi, massage, fitness center, parking, laundry and accommodation services for a complete experience in the heart of Tehran.',
    sectionTitle: 'Services that complete your stay',
    alt: 'Laleh Hotel Facilities',
    headline: 'After busy Tehran, enter the golden silence',
    description: 'The facilities page is designed to connect to spa, gym and VIP service booking modules. In the current version, all CTAs lead users to the contact or booking page.'
  },
  branches: {
    eyebrow: 'Laleh Hotels Group',
    title: 'One brand, multiple Iranian experiences',
    text: 'From central Tehran to the rocky village of Kandovan, the wellness springs of Sareyn, the historic Bistoon caravanserai and the coast of Chabahar, every Laleh property tells a different story.',
    cta: 'View hotel',
    detailTitle: 'The experience',
    otherTitle: 'Other Laleh destinations',
  },
  tehran: {
    title: 'Attractions Around Laleh Hotels',
    sectionTitle: 'From your room to cultural Tehran in minutes',
    headline: 'Personalized Tehran Tour Program',
    text: 'The hotel concierge can plan art, history, shopping, food and business routes with precise timing for you.',
    hotel: 'Laleh Tehran Hotel',
    park: 'Laleh Park',
    museum: 'Museum of Contemporary Art',
    carpet: 'Carpet Museum',
    heroText: 'Adjacent to Laleh Park, near the Museum of Contemporary Art, Valiasr Square and central business districts of Tehran.',
  },
  footer: {
    aboutText: 'Laleh International Hotels Group with over 50 years of Iranian hospitality; from Tehran to Kandovan, Sareyn, Bistoon and Chabahar.',
    explore: 'Explore',
    experience: 'Experience',
    contact: 'Contact',
    since: 'Since 1970',
  },
  notFound: {
    title: 'This room is not available!',
    text: 'The page you\'re looking for was not found. Continue from the main site routes.',
    cta: 'Back to Home'
  },
  quick: ['Free parking', 'High-speed Wi‑Fi', 'Pool & sauna', '24h reception'],
    aboutMini: {
    eyebrow: 'About Laleh Hotels Group',
    title: 'A memorable stay with authentic heritage',
    text: 'Laleh International Hotels Group has hosted local and international guests for more than 55 years, delivering a distinctive expression of Iranian hospitality with modern hotel services.',
    more: 'Learn more',
    facilities: 'Hotel facilities'
  },
  common: { details: 'Details', reserve: 'Book', viewAll: 'View all', from: 'From' },
  editor: { h2: 'Heading 2', h3: 'Heading 3', bold: 'Bold', italic: 'Italic', underline: 'Underline', ul: 'Unordered list', ol: 'Ordered list', link: 'Link' },
  admin: {
    dashboard: 'Dashboard',
    reservations: 'Reservations',
    posts: 'Posts',
    loginTitle: 'Admin Panel',
    loginPassword: 'Enter password',
    loginError: 'Wrong password',
    loginButton: 'Login',
    defaultAuthor: 'Hotel Manager',
    postSaved: 'Post saved ✓',
    postPublished: 'Post published ✓',
    postUpdated: 'Post updated ✓',
    deleteConfirm: 'Are you sure you want to delete this post?',
    postDeleted: 'Post deleted',
    adminPanel: 'Laleh Hotel Admin Panel',
    logout: 'Logout',
    totalBookings: 'Total Bookings',
    blogPosts: 'Blog Posts',
    totalRevenue: 'Total Revenue (Toman)',
    categories: 'Categories',
    recentBookings: 'Recent Bookings',
    noBookings: 'No bookings yet',
    guest: 'Guest',
    room: 'Room',
    amount: 'Amount',
    date: 'Date',
    currencyUnit: 'Toman',
    popularTags: 'Popular Tags',
    noTags: 'No tags yet',
    postCount: 'posts',
    searchPlaceholder: 'Search code / name / phone / email...',
    noSearchResults: 'No booking found with this info',
    newPost: 'New Post',
    firstPost: 'Add your first post',
    edit: 'Edit',
    delete: 'Delete',
    editPost: 'Edit Post',
    newPostTitle: 'New Post',
    titleField: 'Title',
    contentField: 'Content',
    imageField: 'Image',
    imageHint: 'Or direct link:',
    authorField: 'Author',
    tagsField: 'Tags (comma separated)',
    tagsPlaceholder: 'news, event',
    saving: 'Saving...',
    saveChanges: 'Save Changes',
    publish: 'Publish',
    code: 'Code',
    phone: 'Phone',
    email: 'Email',
    checkin: 'Check-in',
    checkout: 'Check-out',
    nights: 'Nights',
    regDate: 'Reg. Date',
    content: 'Content',
  }
};

const RATES = { toman: 1, usd: 715000, eur: 780000 };

export function UIProvider({ children }) {
  const [lang, setLang] = useState(() => localStorage.getItem('laleh-lang') || 'fa');
  const [theme, setTheme] = useState(() => localStorage.getItem('laleh-theme') || 'light');
  const [currency, setCurrency] = useState(() => localStorage.getItem('laleh-currency') || 'toman');

  useEffect(() => {
    localStorage.setItem('laleh-lang', lang);
    document.documentElement.lang = lang;
    document.documentElement.dir = dictionary[lang].dir;
  }, [lang]);

  useEffect(() => {
    localStorage.setItem('laleh-theme', theme);
    document.documentElement.dataset.theme = theme;
  }, [theme]);

  useEffect(() => {
    localStorage.setItem('laleh-currency', currency);
  }, [currency]);

  const dictionary = useMemo(() => ({ fa, en }), []);

  const value = useMemo(() => ({
    lang,
    theme,
    currency,
    t: dictionary[lang],
    rates: RATES,
    toggleLang: () => setLang((v) => (v === 'fa' ? 'en' : 'fa')),
    toggleTheme: () => setTheme((v) => (v === 'light' ? 'dark' : 'light')),
    setCurrency,
    setLang,
    setTheme
  }), [lang, theme, currency, dictionary]);

  return <UIContext.Provider value={value}>{children}</UIContext.Provider>;
}

export const useUI = () => useContext(UIContext);
